-- MySQL Script generated by MySQL Workbench
-- Tue 15 Dec 2015 15:49:24 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teams_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teams_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teams_test` DEFAULT CHARACTER SET utf8 ;
USE `teams_test` ;

-- -----------------------------------------------------
-- Table `teams_test`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teams_test`.`Member` ;

CREATE TABLE IF NOT EXISTS `teams_test`.`Member` (
  `idMember` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(100) NOT NULL,
  `idWorker` INT NOT NULL,
  PRIMARY KEY (`idMember`),
  UNIQUE INDEX `idWorker_UNIQUE` (`idWorker` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teams_test`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teams_test`.`Team` ;

CREATE TABLE IF NOT EXISTS `teams_test`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `dateOfCreation` DATE NOT NULL,
  `idSupervisor` INT NULL,
  PRIMARY KEY (`idTeam`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Team_Member_idx` (`idSupervisor` ASC),
  UNIQUE INDEX `idSupervisor_UNIQUE` (`idSupervisor` ASC),
  CONSTRAINT `fk_Team_Member`
    FOREIGN KEY (`idSupervisor`)
    REFERENCES `teams_test`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teams_test`.`TeamMembers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teams_test`.`TeamMembers` ;

CREATE TABLE IF NOT EXISTS `teams_test`.`TeamMembers` (
  `idTeam` INT NOT NULL,
  `idMember` INT NOT NULL,
  PRIMARY KEY (`idTeam`, `idMember`),
  INDEX `fk_TeamMembers_Member1_idx` (`idMember` ASC),
  CONSTRAINT `fk_TeamMembers_Team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `teams_test`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TeamMembers_Member1`
    FOREIGN KEY (`idMember`)
    REFERENCES `teams_test`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
